apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orders
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: ""
# No scopes means all apps can use it (broader than the previous restricted scope)